#!/usr/bin/env node

/**
 * Module dependencies.
 */

require('../app/pages/pages.order');
// require('./restfulAPI/apiURLConstants');
require('./res/constants/statusCodeString');
require('./res/constants/logString');


//load serverConfig.js
const app = require('./config/serverConfig');

//set up api ===========================================
require('./restfulAPI/login/routes')(app);
require('./restfulAPI/register/routes')(app);
require('./restfulAPI/myProject/createProject/routes')(app);
require('./restfulAPI/myNewPage/routes')(app);


