#!/usr/bin/env node

/**
 * Module dependencies.
 */

require('../app/pages/pages.order');
require('./restfulAPI/apiURLConstants');
require('./res/constants/statusCodeString');
require('./res/constants/logString');


//load serverConfig.js
const app = require('./config/serverConfig');

//set up api ===========================================
require('./restfulAPI/login/login.routes')(app);
require('./restfulAPI/register/register.routes')(app);
require('./restfulAPI/myProject/createProject/createProject.routes')(app);
require('./restfulAPI/myNewPage/todo.routes')(app);
require('./restfulAPI/forms/paymentForm/paymentForm.routes')(app);
require('./restfulAPI/forms/workHourTableForm/workHourTableForm.routes')(app);
require('./restfulAPI/forms/holidayDataForm/holidayDataForm.routes')(app);
require('./restfulAPI/userEdit/userEdit.routes')(app);


