#!/usr/bin/env node

/**
 * Module dependencies.
 */

//load serverConfig.js
var app = require('./config/serverConfig');

//set up api ===========================================
require('./myNewPage/routes')(app);


